#!/bin/bash
# Meant to be run from cron. Reads the config file and makes sure there's an instance running of the main script for 
# each line in the config file.

scriptPath=$(dirname $0)
watchScript=`basename "$0"`
logScript=${watchScript#'watch'}

#echo $scriptPath
#echo $logScript

i=0;
while read j; do
   if [ ${j:0:1} != "#" ]; then
      apiList[$i]=$( cut -d ':' -f 1 <<< "$j" )
      i=$(($i+1));
   fi
done < $scriptPath/conf/$logScript.conf

baseDir="/var/log/syslog/HOSTS/"

logDate=$(date -u +%Y/%m/%d)

#echo $logDate
#echo $apiName


for apiName in "${apiList[@]}"
do

   apiLogDir="$baseDir$logDate/$apiName"

   if [ ! -e $apiLogDir  ]; then
      echo "ERROR: $apiLogDir doesn't exist"
      continue
   fi

   #echo $apiLogDir

   ipDirs=$(ls -d $apiLogDir/ip*)

   ipArr=($ipDirs)

   for i in "${ipArr[@]}"
   do
      #echo $i
      if [  -e $i/user.log  ]; then
         ip=$(basename $i)
         psInfo=$(ps aux | grep "$logScript -i $ip " | grep -v grep )
         if [ -z "$psInfo" ]; then
            echo `date`" i should be doing the following:  nohup $scriptPath/$logScript -i $ip -a $apiName &"
            nohup $scriptPath/$logScript -i $ip -a $apiName &
         fi
      fi
   done

done
